package frc.robot.config;

import static edu.wpi.first.units.Units.Amps;
import static edu.wpi.first.units.Units.Hertz;
import static edu.wpi.first.units.Units.Inches;
import static edu.wpi.first.units.Units.KilogramSquareMeters;
import static edu.wpi.first.units.Units.MetersPerSecond;
import static edu.wpi.first.units.Units.MetersPerSecondPerSecond;
import static edu.wpi.first.units.Units.Milliseconds;
import static edu.wpi.first.units.Units.Rotations;
import static edu.wpi.first.units.Units.RotationsPerSecond;
import static edu.wpi.first.units.Units.RotationsPerSecondPerSecond;
import static edu.wpi.first.units.Units.Volts;

import com.ctre.phoenix6.CANBus;
import com.ctre.phoenix6.configs.CANcoderConfiguration;
import com.ctre.phoenix6.configs.CurrentLimitsConfigs;
import com.ctre.phoenix6.configs.Pigeon2Configuration;
import com.ctre.phoenix6.configs.Slot0Configs;
import com.ctre.phoenix6.configs.TalonFXConfiguration;
import com.ctre.phoenix6.signals.StaticFeedforwardSignValue;
import com.ctre.phoenix6.swerve.SwerveDrivetrainConstants;
import com.ctre.phoenix6.swerve.SwerveModuleConstants;
import com.ctre.phoenix6.swerve.SwerveModuleConstants.ClosedLoopOutputType;
import com.ctre.phoenix6.swerve.SwerveModuleConstants.DriveMotorArrangement;
import com.ctre.phoenix6.swerve.SwerveModuleConstants.SteerFeedbackType;
import com.ctre.phoenix6.swerve.SwerveModuleConstants.SteerMotorArrangement;
import com.ctre.phoenix6.swerve.SwerveModuleConstantsFactory;
import edu.wpi.first.units.measure.Angle;
import edu.wpi.first.units.measure.AngularAcceleration;
import edu.wpi.first.units.measure.AngularVelocity;
import edu.wpi.first.units.measure.Current;
import edu.wpi.first.units.measure.Distance;
import edu.wpi.first.units.measure.Frequency;
import edu.wpi.first.units.measure.LinearAcceleration;
import edu.wpi.first.units.measure.LinearVelocity;
import edu.wpi.first.units.measure.Time;
import java.util.Optional;

// Generated by the 2026 Tuner X Swerve Project Generator
// https://v6.docs.ctr-electronics.com/en/stable/docs/tuner/tuner-swerve/index.html
public final class SwerveConfig {
    public static class ModuleConfig {
        public final Distance xPos, yPos;
        public final String driveMotorName, steerMotorName, encoderName;
        public final int driveCANID, steerCANID, encoderCANID;
        public final int driveChannelID, steerChannelID, encoderChannelID;
        public final boolean driveInverted, steerInverted, encoderInverted;

        public final Angle encoderOffset;

        public final SwerveModuleConstants<TalonFXConfiguration, TalonFXConfiguration, CANcoderConfiguration> constants;

        public ModuleConfig(
                String _prefix,
                Distance _xPos,
                Distance _yPos,
                String _driveMotorName,
                int _driveCANID,
                int _driveChannelID,
                boolean _driveInverted,
                String _steerMotorName,
                int _steerCANID,
                int _steerChannelID,
                boolean _steerInverted,
                String _encoderName,
                int _encoderCANID,
                int _encoderChannelID,
                boolean _encoderInverted,
                Angle _encoderOffset) {
            xPos = _xPos;
            yPos = _yPos;

            driveMotorName = _driveMotorName;
            driveCANID = _driveCANID;
            driveChannelID = _driveChannelID;
            driveInverted = _driveInverted;

            steerMotorName = _steerMotorName;
            steerCANID = _steerCANID;
            steerChannelID = _steerChannelID;
            steerInverted = _steerInverted;

            encoderName = _encoderName;
            encoderCANID = _encoderCANID;
            encoderChannelID = _encoderChannelID;
            encoderInverted = _encoderInverted;
            encoderOffset = _encoderOffset;

            constants = moduleConstantsFactory.createModuleConstants(
                    steerCANID,
                    driveCANID,
                    encoderCANID,
                    encoderOffset,
                    xPos,
                    yPos,
                    driveInverted,
                    steerInverted,
                    encoderInverted);
        }
    }

    public static final String systemName = "Swerve";

    // TODO: characterize and tune swerve
    // The stator current at which the wheels start to slip;
    // This needs to be tuned to your individual robot
    private static final Current slipCurrent = Amps.of(120);

    // Both sets of gains need to be tuned to your individual robot.

    // The steer motor uses any SwerveModule.SteerRequestType control request with the
    // output type specified by SwerveModuleConstants.SteerMotorClosedLoopOutput
    private static final Slot0Configs steerGains = new Slot0Configs()
            .withKP(100)
            .withKI(0)
            .withKD(0.5)
            .withKS(0.1)
            .withKV(1.91)
            .withKA(0)
            .withStaticFeedforwardSign(StaticFeedforwardSignValue.UseClosedLoopSign);
    // When using closed-loop control, the drive motor uses the control
    // output type specified by SwerveModuleConstants.DriveMotorClosedLoopOutput
    private static final Slot0Configs driveGains =
            new Slot0Configs().withKP(0.1).withKI(0).withKD(0).withKS(0).withKV(0.124);

    // Initial configs for the drive and steer motors and the azimuth encoder; these cannot be null.
    // Some configs will be overwritten; check the `with*InitialConfigs()` API documentation.
    private static final TalonFXConfiguration driveInitialConfigs = new TalonFXConfiguration()
            .withCurrentLimits(new CurrentLimitsConfigs()
                    // .withStatorCurrentLimit(120)
                    // .withStatorCurrentLimitEnable(true)
                    .withSupplyCurrentLimit(70)
                    .withSupplyCurrentLimitEnable(true)
                    .withSupplyCurrentLowerLimit(60)
                    .withSupplyCurrentLowerTime(1));
    // .withOpenLoopRamps(new OpenLoopRampsConfigs().withVoltageOpenLoopRampPeriod(Seconds.of(0.25)));
    private static final TalonFXConfiguration steerInitialConfigs = new TalonFXConfiguration()
            .withCurrentLimits(new CurrentLimitsConfigs()
                    // Swerve azimuth does not require much torque output, so we can set a relatively low
                    // stator current limit to help avoid brownouts without impacting performance.
                    .withStatorCurrentLimit(Amps.of(40))
                    .withStatorCurrentLimitEnable(true));
    private static final CANcoderConfiguration encoderInitialConfigs = new CANcoderConfiguration();
    // Configs for the Pigeon 2; leave this null to skip applying Pigeon 2 configs
    private static final Optional<Pigeon2Configuration> pigeonConfigs = Optional.empty();

    // Theoretical free speed (m/s) at 12 V applied output;
    // This needs to be tuned to your individual robot
    public static final LinearVelocity speedAt12Volts = MetersPerSecond.of(4.87);

    public static final LinearVelocity maxTranslationVel = MetersPerSecond.of(4.5);
    public static final AngularVelocity maxAngularVel = RotationsPerSecond.of(1.5);

    public static final double headingP = 10;
    public static final double headingI = 0;
    public static final double headingD = 0;

    public static final double autonTranslationP = 10;
    public static final double autonTranslationI = 0;
    public static final double autonTranslationD = 0;

    public static final LinearAcceleration teleopTranslationAcceleration = MetersPerSecondPerSecond.of(24);
    public static final AngularAcceleration teleopAngularAcceleration = RotationsPerSecondPerSecond.of(12);

    public static final Time simLoopPeriod = Milliseconds.of(4);
    public static final Frequency odometryFrequency = Hertz.of(250);

    public static final SwerveDrivetrainConstants drivetrainConstants = new SwerveDrivetrainConstants()
            .withCANBusName(CANivoreConfig.busID)
            .withPigeon2Id(PigeonConfig.canID)
            .withPigeon2Configs(pigeonConfigs.orElse(null));

    private static final SwerveModuleConstantsFactory<TalonFXConfiguration, TalonFXConfiguration, CANcoderConfiguration>
            moduleConstantsFactory = new SwerveModuleConstantsFactory<
                            TalonFXConfiguration, TalonFXConfiguration, CANcoderConfiguration>()
                    .withDriveMotorGearRatio(6.746031746031747)
                    .withSteerMotorGearRatio(21.428571428571427)
                    .withCouplingGearRatio(3.5714285714285716)
                    .withWheelRadius(Inches.of(2.005))
                    .withSteerMotorGains(steerGains)
                    .withDriveMotorGains(driveGains)
                    .withSteerMotorClosedLoopOutput(ClosedLoopOutputType.TorqueCurrentFOC)
                    .withDriveMotorClosedLoopOutput(ClosedLoopOutputType.TorqueCurrentFOC)
                    .withSlipCurrent(slipCurrent)
                    .withSpeedAt12Volts(speedAt12Volts)
                    .withDriveMotorType(DriveMotorArrangement.TalonFX_Integrated)
                    .withSteerMotorType(SteerMotorArrangement.TalonFX_Integrated)
                    .withFeedbackSource(SteerFeedbackType.FusedCANcoder)
                    .withDriveMotorInitialConfigs(driveInitialConfigs)
                    .withSteerMotorInitialConfigs(steerInitialConfigs)
                    .withEncoderInitialConfigs(encoderInitialConfigs)
                    .withSteerInertia(KilogramSquareMeters.of(0.01)) // used for sim only
                    .withDriveInertia(KilogramSquareMeters.of(0.01)) // used for sim only
                    .withSteerFrictionVoltage(Volts.of(0.2)) // used for sim only
                    .withDriveFrictionVoltage(Volts.of(0.2)); // used for sim only

    public static final ModuleConfig[] modules = {
        new ModuleConfig(
                "fl",
                Inches.of(10.875),
                Inches.of(10.875),
                "flDrive",
                10,
                10,
                false,
                "flSteer",
                11,
                11,
                true,
                "flEncoder",
                21,
                0, // TODO: flEncoder channel id
                false,
                Rotations.of(-0.10546875)),
        new ModuleConfig(
                "fr",
                Inches.of(10.875),
                Inches.of(-10.875),
                "frDrive",
                19,
                19,
                true,
                "frSteer",
                18,
                18,
                true,
                "frEncoder",
                22,
                0, // TODO: frEncoder channel id
                false,
                Rotations.of(-0.3525390625)),
        new ModuleConfig(
                "bl",
                Inches.of(-10.875),
                Inches.of(10.875),
                "blDrive",
                2,
                2,
                false,
                "blSteer",
                1,
                1,
                true,
                "blEncoder",
                23,
                0, // TODO: blEncoder channel id
                false,
                Rotations.of(0.07081)),
        new ModuleConfig(
                "br",
                Inches.of(-10.875),
                Inches.of(-10.875),
                "brDrive",
                9,
                9,
                true,
                "brSteer",
                8,
                8,
                true,
                "brEncoder",
                24,
                0, // TODO: brEncoder channel id
                false,
                Rotations.of(0.016845703125))
    };

    public static final class PigeonConfig {
        public static final String imuName = "pigeon2";
        public static final int canID = 25;
        public static final int channelID = 0; // TODO: pigeon2 channel id
    }

    public static final class CANivoreConfig {
        public static final String busName = "swerveCANivore";
        public static final String busID = "SwerveBus";
        public static final int channelID = 0; // TODO: canivore channel id

        public static final CANBus bus = new CANBus(busID);
    }

    public static final double driveBaseRadius_m = Math.max(
            Math.max(
                    Math.hypot(modules[0].constants.LocationX, modules[0].constants.LocationY),
                    Math.hypot(modules[1].constants.LocationX, modules[1].constants.LocationY)),
            Math.max(
                    Math.hypot(modules[2].constants.LocationX, modules[2].constants.LocationY),
                    Math.hypot(modules[3].constants.LocationX, modules[3].constants.LocationY)));

    private SwerveConfig() {}
}
