package frc.robot.subsystems.swerve;

import static edu.wpi.first.units.Units.Second;
import static edu.wpi.first.units.Units.Seconds;
import static edu.wpi.first.units.Units.Volts;

import choreo.trajectory.SwerveSample;
import com.ctre.phoenix6.BaseStatusSignal;
import com.ctre.phoenix6.SignalLogger;
import com.ctre.phoenix6.StatusSignal;
import com.ctre.phoenix6.Utils;
import com.ctre.phoenix6.hardware.CANcoder;
import com.ctre.phoenix6.hardware.Pigeon2;
import com.ctre.phoenix6.hardware.TalonFX;
import com.ctre.phoenix6.swerve.SwerveDrivetrain;
import com.ctre.phoenix6.swerve.SwerveRequest;
import edu.wpi.first.math.Matrix;
import edu.wpi.first.math.controller.PIDController;
import edu.wpi.first.math.geometry.Pose2d;
import edu.wpi.first.math.geometry.Rotation2d;
import edu.wpi.first.math.kinematics.ChassisSpeeds;
import edu.wpi.first.math.kinematics.SwerveModuleState;
import edu.wpi.first.math.numbers.N1;
import edu.wpi.first.math.numbers.N3;
import edu.wpi.first.units.measure.Angle;
import edu.wpi.first.units.measure.AngularVelocity;
import edu.wpi.first.units.measure.LinearAcceleration;
import edu.wpi.first.wpilibj.Alert;
import edu.wpi.first.wpilibj.Notifier;
import edu.wpi.first.wpilibj.RobotController;
import edu.wpi.first.wpilibj2.command.Command;
import edu.wpi.first.wpilibj2.command.CommandScheduler;
import edu.wpi.first.wpilibj2.command.Subsystem;
import edu.wpi.first.wpilibj2.command.sysid.SysIdRoutine;
import frc.robot.Robot;
import frc.robot.RobotContainer;
import frc.robot.config.Overrides;
import frc.robot.config.SwerveConfig;
import frc.robot.config.SwerveConfig.CANivoreConfig;
import frc.robot.config.SwerveConfig.PigeonConfig;
import frc.robot.constants.FieldConstants;
import frc.robot.telemetry.Telemetry;
import frc.robot.telemetry.TelemetryUnits;
import frc.robot.telemetry.writer.BoolWriter;
import frc.robot.telemetry.writer.DoubleWriter;
import frc.robot.telemetry.writer.StringWriter;
import frc.robot.telemetry.writer.StructArrayWriter;
import frc.robot.telemetry.writer.StructWriter;
import frc.robot.telemetry.writer.compound.SubsystemWriter;
import frc.robot.util.AlertUtils;
import java.util.Optional;
import java.util.function.Supplier;

/**
 * Class that extends the Phoenix 6 SwerveDrivetrain class and implements
 * Subsystem so it can easily be used in command-based projects.
 *
 * Generated by the 2026 Tuner X Swerve Project Generator
 * https://v6.docs.ctr-electronics.com/en/stable/docs/tuner/tuner-swerve/index.html
 */
public class Swerve extends SwerveDrivetrain<TalonFX, TalonFX, CANcoder> implements Subsystem {
    private Notifier m_simNotifier = null;
    private double m_lastSimTime;

    private boolean hasAppliedPerspective = false;
    private boolean lastAppliedPerspectiveIsRed = false;

    private final SwerveRequest.ApplyFieldSpeeds trajFollowReq = new SwerveRequest.ApplyFieldSpeeds();
    private final PIDController trajXController = new PIDController(
            SwerveConfig.autonTranslationP, SwerveConfig.autonTranslationI, SwerveConfig.autonTranslationD);
    private final PIDController trajYController = new PIDController(
            SwerveConfig.autonTranslationP, SwerveConfig.autonTranslationI, SwerveConfig.autonTranslationD);
    private final PIDController trajThetaController =
            new PIDController(SwerveConfig.headingP, SwerveConfig.headingI, SwerveConfig.headingD);

    /* Swerve requests to apply during SysId characterization */
    private final SwerveRequest.SysIdSwerveTranslation m_translationCharacterization =
            new SwerveRequest.SysIdSwerveTranslation();
    private final SwerveRequest.SysIdSwerveSteerGains m_steerCharacterization =
            new SwerveRequest.SysIdSwerveSteerGains();
    private final SwerveRequest.SysIdSwerveRotation m_rotationCharacterization =
            new SwerveRequest.SysIdSwerveRotation();

    /* SysId routine for characterizing translation. This is used to find PID gains for the drive motors. */
    private final SysIdRoutine m_sysIdRoutineTranslation = new SysIdRoutine(
            new SysIdRoutine.Config(
                    null, // Use default ramp rate (1 V/s)
                    Volts.of(4), // Reduce dynamic step voltage to 4 V to prevent brownout
                    null, // Use default timeout (10 s)
                    // Log state with SignalLogger class
                    state -> SignalLogger.writeString("SysIdTranslation_State", state.toString())),
            new SysIdRoutine.Mechanism(
                    output -> setControl(m_translationCharacterization.withVolts(output)), null, this));

    /* SysId routine for characterizing steer. This is used to find PID gains for the steer motors. */
    @SuppressWarnings("unused")
    private final SysIdRoutine m_sysIdRoutineSteer = new SysIdRoutine(
            new SysIdRoutine.Config(
                    null, // Use default ramp rate (1 V/s)
                    Volts.of(7), // Use dynamic voltage of 7 V
                    null, // Use default timeout (10 s)
                    // Log state with SignalLogger class
                    state -> SignalLogger.writeString("SysIdSteer_State", state.toString())),
            new SysIdRoutine.Mechanism(volts -> setControl(m_steerCharacterization.withVolts(volts)), null, this));

    /*
     * SysId routine for characterizing rotation.
     * This is used to find PID gains for the FieldCentricFacingAngle HeadingController.
     * See the documentation of SwerveRequest.SysIdSwerveRotation for info on importing the log to SysId.
     */
    @SuppressWarnings("unused")
    private final SysIdRoutine m_sysIdRoutineRotation = new SysIdRoutine(
            new SysIdRoutine.Config(
                    /* This is in radians per second², but SysId only supports "volts per second" */
                    Volts.of(Math.PI / 6).per(Second),
                    /* This is in radians per second, but SysId only supports "volts" */
                    Volts.of(Math.PI),
                    null, // Use default timeout (10 s)
                    // Log state with SignalLogger class
                    state -> SignalLogger.writeString("SysIdRotation_State", state.toString())),
            new SysIdRoutine.Mechanism(
                    output -> {
                        /* output is actually radians per second, but SysId only supports "volts" */
                        setControl(m_rotationCharacterization.withRotationalRate(output.in(Volts)));
                        /* also log the requested output for SysId */
                        SignalLogger.writeDouble("Rotational_Rate", output.in(Volts));
                    },
                    null,
                    this));

    /* The SysId routine to test */
    private final SysIdRoutine m_sysIdRoutineToApply = m_sysIdRoutineTranslation;

    private final SubsystemWriter<Swerve> subsystemWriter =
            Telemetry.makeSubsystemWriter(this, "/", SwerveConfig.systemName);
    private final StringWriter controlWriter =
            Telemetry.makeStringWriter(SwerveConfig.systemName, "controllingRequest");
    private final DoubleWriter odometryFrequencyWriter =
            Telemetry.makeDoubleWriter(SwerveConfig.systemName, "odometryFrequency", TelemetryUnits.hertz);
    private final StructWriter<Pose2d> robotPoseWriter =
            Telemetry.makePose2dWriter(SwerveConfig.systemName, "robotPose");
    private final StructWriter<ChassisSpeeds> chassisSpeedsWriter =
            Telemetry.makeChassisSpeedsWriter(SwerveConfig.systemName, "chassisSpeeds");
    private final StructArrayWriter<SwerveModuleState> moduleStatesWriter =
            Telemetry.makeSwerveModuleStateArrayWriter(SwerveConfig.systemName, "moduleStates");
    private final StructArrayWriter<SwerveModuleState> moduleTargetsWriter =
            Telemetry.makeSwerveModuleStateArrayWriter(SwerveConfig.systemName, "moduleTargets");

    private PigeonBuffer pigeonBuffer = new PigeonBuffer();
    private boolean pigeonConnectedLast = false;
    private boolean pigeonBreakerLast = false;
    private final StatusSignal<AngularVelocity> pigeonAngularVelXWorldSignal;
    private final StatusSignal<AngularVelocity> pigeonAngularVelYWorldSignal;
    private final StatusSignal<AngularVelocity> pigeonAngularVelZWorldSignal;
    private final StatusSignal<Angle> pigeonRollSignal;
    private final StatusSignal<Angle> pigeonPitchSignal;
    private final StatusSignal<Angle> pigeonYawSignal;
    private final StatusSignal<LinearAcceleration> pigeonAccelXSignal;
    private final StatusSignal<LinearAcceleration> pigeonAccelYSignal;
    private final StatusSignal<LinearAcceleration> pigeonAccelZSignal;

    private final BoolWriter pigeonConnectedWriter;
    private final BoolWriter pigeonCANWriter;
    private final Alert pigeonCANAlert;
    private final BoolWriter pigeonBreakerWriter;
    private final Alert pigeonBreakerAlert;
    private final DoubleWriter pigeonAngularVelXWorldWriter;
    private final DoubleWriter pigeonAngularVelYWorldWriter;
    private final DoubleWriter pigeonAngularVelZWorldWriter;
    private final DoubleWriter pigeonRollWriter;
    private final DoubleWriter pigeonPitchWriter;
    private final DoubleWriter pigeonYawWriter;
    private final DoubleWriter pigeonAccelXWriter;
    private final DoubleWriter pigeonAccelYWriter;
    private final DoubleWriter pigeonAccelZWriter;

    private boolean canivoreBreakerLast = false;

    private final BoolWriter canivoreBreakerWriter;
    private final Alert canivoreBreakerAlert;

    private final ModuleHelper[] helpers;
    private final ModuleReport[] moduleReports;

    private boolean thermalShutdown = false;
    private boolean thermalShutdownLast = false;

    /**
     * Constructs a CTRE SwerveDrivetrain using the specified constants.
     * <p>
     * This constructs the underlying hardware devices, so users should not construct
     * the devices themselves. If they need the devices, they can access them through
     * getters in the classes.
     */
    public Swerve() {
        super(
                TalonFX::new,
                TalonFX::new,
                CANcoder::new,
                SwerveConfig.drivetrainConstants,
                SwerveConfig.modules[0].constants,
                SwerveConfig.modules[1].constants,
                SwerveConfig.modules[2].constants,
                SwerveConfig.modules[3].constants);

        helpers = new ModuleHelper[] {
            new ModuleHelper(0, getModule(0)),
            new ModuleHelper(1, getModule(1)),
            new ModuleHelper(2, getModule(2)),
            new ModuleHelper(3, getModule(3))
        };
        moduleReports =
                new ModuleReport[] {new ModuleReport(), new ModuleReport(), new ModuleReport(), new ModuleReport()};

        {
            String pigeonTable = SwerveConfig.systemName + "/pigeonBuffer";

            Pigeon2 pigeon = getPigeon2();
            pigeonAngularVelXWorldSignal = pigeon.getAngularVelocityXWorld(false);
            pigeonAngularVelYWorldSignal = pigeon.getAngularVelocityYWorld(false);
            pigeonAngularVelZWorldSignal = pigeon.getAngularVelocityZWorld(false);
            pigeonRollSignal = pigeon.getRoll(false);
            pigeonPitchSignal = pigeon.getPitch(false);
            pigeonYawSignal = pigeon.getYaw(false);
            pigeonAccelXSignal = pigeon.getAccelerationX(false);
            pigeonAccelYSignal = pigeon.getAccelerationY(false);
            pigeonAccelZSignal = pigeon.getAccelerationZ(false);

            pigeonConnectedWriter = Telemetry.makeBoolWriter(pigeonTable, "connected");
            pigeonCANWriter =
                    Telemetry.makeBoolWriter("CAN", String.format("%s_%s", PigeonConfig.imuName, PigeonConfig.canID));
            pigeonCANAlert = AlertUtils.makeCANFailureAlert(PigeonConfig.imuName);
            pigeonBreakerWriter = Telemetry.makeBoolWriter(SwerveConfig.systemName, "pigeonBreakerTripped");
            pigeonBreakerAlert = AlertUtils.makeBreakerTripAlert(PigeonConfig.imuName);
            pigeonAngularVelXWorldWriter =
                    Telemetry.makeDoubleWriter(pigeonTable, "angularVelXWorld", TelemetryUnits.degPerSec);
            pigeonAngularVelYWorldWriter =
                    Telemetry.makeDoubleWriter(pigeonTable, "angularVelYWorld", TelemetryUnits.degPerSec);
            pigeonAngularVelZWorldWriter =
                    Telemetry.makeDoubleWriter(pigeonTable, "angularVelZWorld", TelemetryUnits.degPerSec);
            pigeonRollWriter = Telemetry.makeDoubleWriter(pigeonTable, "roll", TelemetryUnits.degrees);
            pigeonPitchWriter = Telemetry.makeDoubleWriter(pigeonTable, "pitch", TelemetryUnits.degrees);
            pigeonYawWriter = Telemetry.makeDoubleWriter(pigeonTable, "yaw", TelemetryUnits.degrees);
            pigeonAccelXWriter = Telemetry.makeDoubleWriter(pigeonTable, "accelX", TelemetryUnits.g);
            pigeonAccelYWriter = Telemetry.makeDoubleWriter(pigeonTable, "accelY", TelemetryUnits.g);
            pigeonAccelZWriter = Telemetry.makeDoubleWriter(pigeonTable, "accelZ", TelemetryUnits.g);
        }

        {
            canivoreBreakerWriter = Telemetry.makeBoolWriter(SwerveConfig.systemName, "canivoreBreakerTripped");
            canivoreBreakerAlert = AlertUtils.makeBreakerTripAlert(CANivoreConfig.busName);
        }

        trajThetaController.enableContinuousInput(-Math.PI, Math.PI);

        registerTelemetry(this::swerveTelemetry);

        if (Utils.isSimulation()) {
            startSimThread();
        }

        // have to manually register because this subsystem only implements Subsystem rather than extending
        // SubsystemBase
        CommandScheduler.getInstance().registerSubsystem(this);
    }

    @Override
    public void periodic() {
        boolean isRed = Robot.instance().brain.state.isRed;
        if (!hasAppliedPerspective || lastAppliedPerspectiveIsRed != isRed) {
            if (lastAppliedPerspectiveIsRed != isRed) {
                // automatically flip pose when changing alliance
                // shouldn't ever happen in a match but is useful for testing
                resetPose(getState().Pose.rotateAround(FieldConstants.fieldCenter, Rotation2d.k180deg));
            }

            lastAppliedPerspectiveIsRed = isRed;
            hasAppliedPerspective = true;
            setOperatorPerspectiveForward(isRed ? Rotation2d.k180deg : Rotation2d.kZero);
        }

        subsystemWriter.update();
    }

    public void report(SwerveReport report) {
        helpers[0].report(moduleReports[0]);
        helpers[1].report(moduleReports[1]);
        helpers[2].report(moduleReports[2]);
        helpers[3].report(moduleReports[3]);

        boolean module0Operational = moduleReports[0].driveOperational
                && moduleReports[0].steerOperational
                && moduleReports[0].encoderOperational;
        boolean module1Operational = moduleReports[1].driveOperational
                && moduleReports[1].steerOperational
                && moduleReports[1].encoderOperational;
        boolean module2Operational = moduleReports[2].driveOperational
                && moduleReports[2].steerOperational
                && moduleReports[2].encoderOperational;
        boolean module3Operational = moduleReports[3].driveOperational
                && moduleReports[3].steerOperational
                && moduleReports[3].encoderOperational;
        boolean pigeonOperational = pigeonReport();
        boolean canivoreOperational = canivoreReport();

        report.isOperational = module0Operational
                && module1Operational
                && module2Operational
                && module3Operational
                && pigeonOperational
                && canivoreOperational;

        boolean module0ThermalShutdown = moduleReports[0].driveThermalShutdown || moduleReports[0].steerThermalShutdown;
        boolean module1ThermalShutdown = moduleReports[1].driveThermalShutdown || moduleReports[1].steerThermalShutdown;
        boolean module2ThermalShutdown = moduleReports[2].driveThermalShutdown || moduleReports[2].steerThermalShutdown;
        boolean module3ThermalShutdown = moduleReports[3].driveThermalShutdown || moduleReports[3].steerThermalShutdown;

        thermalShutdown =
                module0ThermalShutdown || module1ThermalShutdown || module2ThermalShutdown || module3ThermalShutdown;

        if (thermalShutdown && !thermalShutdownLast) {
            stop();
        }

        thermalShutdownLast = thermalShutdown;
    }

    private boolean pigeonReport() {
        Pigeon2 pigeon = getPigeon2();

        pigeonBuffer.connected = pigeon.isConnected();
        if (pigeonBuffer.connected) {
            BaseStatusSignal.refreshAll(
                    pigeonAngularVelXWorldSignal,
                    pigeonAngularVelYWorldSignal,
                    pigeonAngularVelZWorldSignal,
                    pigeonRollSignal,
                    pigeonPitchSignal,
                    pigeonYawSignal,
                    pigeonAccelXSignal,
                    pigeonAccelYSignal,
                    pigeonAccelZSignal);

            pigeonBuffer.angularVelXWorld_DPS = pigeonAngularVelXWorldSignal.getValueAsDouble();
            pigeonBuffer.angularVelYWorld_DPS = pigeonAngularVelYWorldSignal.getValueAsDouble();
            pigeonBuffer.angularVelZWorld_DPS = pigeonAngularVelZWorldSignal.getValueAsDouble();
            pigeonBuffer.roll_deg = pigeonRollSignal.getValueAsDouble();
            pigeonBuffer.pitch_deg = pigeonPitchSignal.getValueAsDouble();
            pigeonBuffer.yaw_deg = pigeonYawSignal.getValueAsDouble();
            pigeonBuffer.accelX_g = pigeonAccelXSignal.getValueAsDouble();
            pigeonBuffer.accelY_g = pigeonAccelYSignal.getValueAsDouble();
            pigeonBuffer.accelZ_g = pigeonAccelZSignal.getValueAsDouble();
        } else {
            pigeonBuffer.angularVelXWorld_DPS = Double.NaN;
            pigeonBuffer.angularVelYWorld_DPS = Double.NaN;
            pigeonBuffer.angularVelZWorld_DPS = Double.NaN;
            pigeonBuffer.roll_deg = Double.NaN;
            pigeonBuffer.pitch_deg = Double.NaN;
            pigeonBuffer.yaw_deg = Double.NaN;
            pigeonBuffer.accelX_g = Double.NaN;
            pigeonBuffer.accelY_g = Double.NaN;
            pigeonBuffer.accelZ_g = Double.NaN;
        }
        boolean breakerTripped = RobotContainer.instance().pdh.isBreakerTripped(PigeonConfig.channelID);

        pigeonConnectedWriter.set(pigeonBuffer.connected);
        pigeonCANWriter.set(pigeonBuffer.connected);
        pigeonCANAlert.set(!pigeonBuffer.connected && !breakerTripped);
        if (pigeonBuffer.connected != pigeonConnectedLast) {
            if (pigeonBuffer.connected) {
                Telemetry.reportCANConnect(PigeonConfig.imuName, PigeonConfig.canID, PigeonConfig.channelID);
            } else {
                Telemetry.reportCANDisconnect(PigeonConfig.imuName, PigeonConfig.canID, PigeonConfig.channelID);
            }
        }
        pigeonBreakerWriter.set(breakerTripped);
        pigeonBreakerAlert.set(breakerTripped);
        if (breakerTripped != pigeonBreakerLast) {
            if (breakerTripped) {
                Telemetry.reportBreakerTrip(PigeonConfig.imuName, PigeonConfig.canID, PigeonConfig.channelID);
            } else {
                Telemetry.reportBreakerReset(PigeonConfig.imuName, PigeonConfig.canID, PigeonConfig.channelID);
            }
        }
        pigeonAngularVelXWorldWriter.set(pigeonBuffer.angularVelXWorld_DPS);
        pigeonAngularVelYWorldWriter.set(pigeonBuffer.angularVelYWorld_DPS);
        pigeonAngularVelZWorldWriter.set(pigeonBuffer.angularVelZWorld_DPS);
        pigeonRollWriter.set(pigeonBuffer.roll_deg);
        pigeonPitchWriter.set(pigeonBuffer.pitch_deg);
        pigeonYawWriter.set(pigeonBuffer.yaw_deg);
        pigeonAccelXWriter.set(pigeonBuffer.accelX_g);
        pigeonAccelYWriter.set(pigeonBuffer.accelY_g);
        pigeonAccelZWriter.set(pigeonBuffer.accelZ_g);

        boolean operational;
        if (Overrides.disableSwerveSafety) {
            operational = true;
        } else {
            operational = pigeonBuffer.connected && !breakerTripped;
        }

        pigeonConnectedLast = pigeonBuffer.connected;
        pigeonBreakerLast = breakerTripped;

        return operational;
    }

    private boolean canivoreReport() {
        boolean breakerTripped = RobotContainer.instance().pdh.isBreakerTripped(CANivoreConfig.channelID);

        canivoreBreakerWriter.set(breakerTripped);
        canivoreBreakerAlert.set(breakerTripped);
        if (breakerTripped != canivoreBreakerLast) {
            if (breakerTripped) {
                Telemetry.reportBreakerTripNoCAN(CANivoreConfig.busName, CANivoreConfig.channelID);
            } else {
                Telemetry.reportBreakerResetNoCAN(CANivoreConfig.busName, CANivoreConfig.channelID);
            }
        }

        boolean operational = !breakerTripped;

        canivoreBreakerLast = breakerTripped;

        return operational;
    }

    private void swerveTelemetry(SwerveDriveState state) {
        odometryFrequencyWriter.set(1 / state.OdometryPeriod);

        robotPoseWriter.set(state.Pose);
        Robot.instance().field.setRobotPose(state.Pose);

        chassisSpeedsWriter.set(state.Speeds);
        moduleStatesWriter.set(state.ModuleStates);
        moduleTargetsWriter.set(state.ModuleTargets);
    }

    /**
     * Returns a command that applies the specified control request to this swerve drivetrain.
     *
     * @param request Function returning the request to apply
     * @return Command to run
     */
    public Command applyRequest(Supplier<SwerveRequest> request) {
        return run(() -> setControl(request.get()));
    }

    @Override
    public void setControl(SwerveRequest request_nl) {
        if (thermalShutdown && request_nl != null) return;

        super.setControl(request_nl);
        controlWriter.set(request_nl == null ? null : request_nl.getClass().getSimpleName());
    }

    public void stop() {
        setControl(null);
    }

    public void followTrajectory(SwerveSample sample) {
        Pose2d currPose = getState().Pose;

        ChassisSpeeds speeds = new ChassisSpeeds(
                sample.vx + trajXController.calculate(currPose.getX(), sample.x),
                sample.vy + trajYController.calculate(currPose.getY(), sample.y),
                sample.omega
                        + trajThetaController.calculate(currPose.getRotation().getRadians(), sample.heading));

        setControl(trajFollowReq
                .withSpeeds(speeds)
                .withWheelForceFeedforwardsX(sample.moduleForcesX())
                .withWheelForceFeedforwardsY(sample.moduleForcesY()));
    }

    /**
     * Runs the SysId Quasistatic test in the given direction for the routine
     * specified by {@link #m_sysIdRoutineToApply}.
     *
     * @param direction Direction of the SysId Quasistatic test
     * @return Command to run
     */
    public Command sysIdQuasistatic(SysIdRoutine.Direction direction) {
        return m_sysIdRoutineToApply.quasistatic(direction);
    }

    /**
     * Runs the SysId Dynamic test in the given direction for the routine
     * specified by {@link #m_sysIdRoutineToApply}.
     *
     * @param direction Direction of the SysId Dynamic test
     * @return Command to run
     */
    public Command sysIdDynamic(SysIdRoutine.Direction direction) {
        return m_sysIdRoutineToApply.dynamic(direction);
    }

    private void startSimThread() {
        m_lastSimTime = Utils.getCurrentTimeSeconds();

        /* Run simulation at a faster rate so PID gains behave more reasonably */
        m_simNotifier = new Notifier(() -> {
            final double currentTime = Utils.getCurrentTimeSeconds();
            double deltaTime = currentTime - m_lastSimTime;
            m_lastSimTime = currentTime;

            /* use the measured time delta, get battery voltage from WPILib */
            updateSimState(deltaTime, RobotController.getBatteryVoltage());
        });
        m_simNotifier.startPeriodic(SwerveConfig.simLoopPeriod.in(Seconds));
    }

    /**
     * Adds a vision measurement to the Kalman Filter. This will correct the odometry pose estimate
     * while still accounting for measurement noise.
     *
     * @param visionRobotPoseMeters The pose of the robot as measured by the vision camera.
     * @param timestampSeconds The timestamp of the vision measurement in seconds.
     */
    @Override
    public void addVisionMeasurement(Pose2d visionRobotPoseMeters, double timestampSeconds) {
        super.addVisionMeasurement(visionRobotPoseMeters, Utils.fpgaToCurrentTime(timestampSeconds));
    }

    /**
     * Adds a vision measurement to the Kalman Filter. This will correct the odometry pose estimate
     * while still accounting for measurement noise.
     * <p>
     * Note that the vision measurement standard deviations passed into this method
     * will continue to apply to future measurements until a subsequent call to
     * {@link #setVisionMeasurementStdDevs(Matrix)} or this method.
     *
     * @param visionRobotPoseMeters The pose of the robot as measured by the vision camera.
     * @param timestampSeconds The timestamp of the vision measurement in seconds.
     * @param visionMeasurementStdDevs Standard deviations of the vision pose measurement
     *     in the form [x, y, theta]ᵀ, with units in meters and radians.
     */
    @Override
    public void addVisionMeasurement(
            Pose2d visionRobotPoseMeters, double timestampSeconds, Matrix<N3, N1> visionMeasurementStdDevs) {
        super.addVisionMeasurement(
                visionRobotPoseMeters, Utils.fpgaToCurrentTime(timestampSeconds), visionMeasurementStdDevs);
    }

    /**
     * Return the pose at a given timestamp, if the buffer is not empty.
     *
     * @param timestampSeconds The timestamp of the pose in seconds.
     * @return The pose at the given timestamp (or Optional.empty() if the buffer is empty).
     */
    @Override
    public Optional<Pose2d> samplePoseAt(double timestampSeconds) {
        return super.samplePoseAt(Utils.fpgaToCurrentTime(timestampSeconds));
    }
}
